# Generated by Django 4.2.1 on 2023-06-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisories", "0001_initial"),
        ("backend", "0004_alter_reportrelease_release_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="advisory",
            name="labels",
            field=models.ManyToManyField(blank=True, null=True, to="advisories.label"),
        ),
    ]
