# Generated by Django 4.2.1 on 2023-07-08 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("backend", "0007_finding_component_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="finding",
            name="host",
        ),
        migrations.RemoveField(
            model_name="finding",
            name="mobile_application",
        ),
        migrations.RemoveField(
            model_name="finding",
            name="service",
        ),
        migrations.RemoveField(
            model_name="finding",
            name="web_application",
        ),
        migrations.AlterField(
            model_name="finding",
            name="component_content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "webapplication")),
                    models.Q(("app_label", "backend"), ("model", "service")),
                    models.Q(("app_label", "backend"), ("model", "host")),
                    models.Q(("app_label", "backend"), ("model", "mobileapplication")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="component_object_id",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
