# Generated by Django 4.2.3 on 2023-07-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0010_project_require_owasp_risk_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='notify_critical_findings',
            field=models.BooleanField(default=False),
        ),
    ]
