# Generated by Django 4.2.4 on 2023-08-20 11:13

import backend.models.finding_attachment
from django.db import migrations, models
import django.db.models.deletion


def migrate_proofs(apps, schema_editor):
    from django.core.files.images import ImageFile
    Finding = apps.get_model("backend.Finding")
    Attachment = apps.get_model("backend.FindingImageAttachment")
    for finding in Finding.objects.all():
        proofs = finding.proof_set.all()
        proof_text = ""
        for proof in proofs:
            proof_text += f"{proof.text}\n"
            if proof.image:
                image_file = ImageFile(proof.image)
                attachment = Attachment.objects.create(finding=finding, image=image_file,
                                                       caption=proof.image_caption)
                attachment.name = proof.title
                attachment.save()
                proof_text += f"![{proof.title}]({attachment.image})\n"
        finding.proof_text = proof_text
        finding.save()


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0015_projectfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindingImageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('image',
                 models.ImageField(max_length=256, upload_to=backend.models.finding_attachment.finding_upload_path)),
                ('name', models.CharField(max_length=128)),
                ('caption', models.CharField(blank=True, max_length=256, null=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.finding')),
            ],
            options={
                'ordering': ['-date_updated'],
            },
        ),
        migrations.AddField(
            model_name='finding',
            name='proof_text',
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.RunPython(migrate_proofs),
        migrations.AlterField(
            model_name='finding',
            name='proof_text',
            field=models.TextField(),
            preserve_default=False
        ),
        migrations.DeleteModel(
            name='Proof',
        ),
    ]
