# Generated by Django 4.2.4 on 2023-08-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0017_alter_finding_proof_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='proof_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='advisory',
            name='proof_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
