# Generated by Django 4.2.4 on 2023-08-21 17:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0018_alter_finding_proof_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdvisoryProof',
        ),
    ]
