# Generated by Django 4.2.4 on 2023-08-23 16:30

import backend.models.company
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0019_delete_advisoryproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, max_length=256, null=True,
                                    upload_to=backend.models.company.upload_path),
        ),
    ]
