# Generated by Django 4.2.4 on 2023-09-10 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0020_company_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expire', models.DateTimeField(null=True)),
                ('prefix', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('key', models.CharField(editable=False, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='apitoken',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='apitoken',
            name='date_last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.project'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='scope_advisories',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Access'), (1, 'Read'), (2, 'Read Write')],
                                                   default=0),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='scope_all_projects',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Access'), (1, 'Read'), (2, 'Read Write')],
                                                   default=0),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='scope_companies',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Access'), (1, 'Read'), (2, 'Read Write')],
                                                   default=0),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='scope_user',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No Access'), (1, 'Read'), (2, 'Read Write')],
                                                   default=0),
        ),
        migrations.AlterField(
            model_name='apitoken',
            name='date_expire',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
