# Generated by Django 4.2.5 on 2023-10-04 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0022_projectcommand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectToken',
        ),
    ]
