# Generated by Django 4.2.5 on 2023-10-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0023_delete_projecttoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.PositiveSmallIntegerField(choices=[(0, 'Denied'), (1, 'Allowed')])),
                ('details', models.CharField(max_length=256)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
