# Generated by Django 4.2.5 on 2023-10-04 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0024_projectscope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectscope',
            options={'ordering': ['pk']},
        ),
    ]
