# Generated by Django 4.2.5 on 2023-10-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_alter_projectscope_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='variant',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pentest PDF'), (1, 'Vulnerability CSV'), (2, 'Pentest Excel')]),
        ),
    ]
