# Generated by Django 4.2.6 on 2023-10-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0026_alter_report_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
