# Generated by Django 4.2.6 on 2023-10-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('backend', '0027_alter_account_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='component_content_type',
            field=models.ForeignKey(
                limit_choices_to=models.Q(models.Q(('app_label', 'backend'), ('model', 'webapplication')),
                                          models.Q(('app_label', 'backend'), ('model', 'service')),
                                          models.Q(('app_label', 'backend'), ('model', 'host')),
                                          models.Q(('app_label', 'backend'), ('model', 'mobileapplication')),
                                          models.Q(('app_label', 'backend'), ('model', 'thickclient')),
                                          _connector='OR'), on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='ThickClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('accessible',
                 models.PositiveSmallIntegerField(choices=[(0, 'Accessible'), (1, 'Not Accessible'), (2, 'Unknown')],
                                                  default=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('environment', models.PositiveSmallIntegerField(
                    choices=[(0, 'Unknown'), (1, 'Production'), (2, 'Testing'), (3, 'Development'), (4, 'Staging')],
                    default=0)),
                ('name', models.CharField(max_length=256)),
                ('version', models.CharField(blank=True, max_length=128)),
                ('os',
                 models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Windows'), (2, 'Linux')], default=0)),
                ('programming_language', models.CharField(default='Unknown', max_length=64)),
                ('decompile_allowed',
                 models.PositiveSmallIntegerField(choices=[(0, 'Unknown'), (1, 'Yes'), (2, 'No')], default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
            options={
                'ordering': ['name', 'version'],
                'unique_together': {('project', 'name')},
            },
        ),
    ]
