# Generated by Django 4.2.6 on 2023-10-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_alter_finding_component_content_type_thickclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
