# Generated by Django 4.2.1 on 2023-06-24 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetchecklist",
            options={"ordering": ["checklist_id"]},
        ),
    ]
