# Generated by Django 4.2.1 on 2023-07-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("checklists", "0002_alter_assetchecklist_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetchecklist",
            name="checklist_id",
            field=models.CharField(max_length=128),
        ),
    ]
