# Generated by Django 4.2.1 on 2023-07-08 12:57

from django.db import migrations, models
import django.db.models.deletion


def migrate_asset_to_component(apps, schema_editor):
    AssetChecklist = apps.get_model('checklists', 'AssetChecklist')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    for checklist in AssetChecklist.objects.all():
        for asset in ["web_application", "host", "service", "mobile_application"]:
            if getattr(checklist, asset):
                check_asset = getattr(checklist, asset)
                break
        checklist.component = check_asset
        checklist.component_object_id = check_asset.pk
        checklist.component_content_type = ContentType.objects.get_for_model(check_asset)
        checklist.save()


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("checklists", "0003_alter_assetchecklist_checklist_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="assetchecklist",
            name="component_content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "webapplication")),
                    models.Q(("app_label", "backend"), ("model", "service")),
                    models.Q(("app_label", "backend"), ("model", "host")),
                    models.Q(("app_label", "backend"), ("model", "mobileapplication")),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="assetchecklist",
            name="component_object_id",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name="assetchecklist",
            index=models.Index(
                fields=["component_content_type", "component_object_id"],
                name="checklists__compone_460dff_idx",
            ),
        ),
        migrations.RunPython(migrate_asset_to_component),
        migrations.RemoveField(
            model_name="assetchecklist",
            name="host",
        ),
        migrations.RemoveField(
            model_name="assetchecklist",
            name="service",
        ),
        migrations.RemoveField(
            model_name="assetchecklist",
            name="web_application",
        ),
        migrations.AlterField(
            model_name="assetchecklist",
            name="component_content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "backend"), ("model", "webapplication")),
                    models.Q(("app_label", "backend"), ("model", "service")),
                    models.Q(("app_label", "backend"), ("model", "host")),
                    models.Q(("app_label", "backend"), ("model", "mobileapplication")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="assetchecklist",
            name="component_object_id",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
