# Generated by Django 4.2.6 on 2023-10-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('checklists', '0004_assetchecklist_component_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetchecklist',
            name='component_content_type',
            field=models.ForeignKey(
                limit_choices_to=models.Q(models.Q(('app_label', 'backend'), ('model', 'webapplication')),
                                          models.Q(('app_label', 'backend'), ('model', 'service')),
                                          models.Q(('app_label', 'backend'), ('model', 'host')),
                                          models.Q(('app_label', 'backend'), ('model', 'mobileapplication')),
                                          models.Q(('app_label', 'backend'), ('model', 'thickclient')),
                                          _connector='OR'), on_delete=django.db.models.deletion.CASCADE,
                to='contenttypes.contenttype'),
        ),
    ]
