DEBUG = True
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
ENABLE_DJANGO_ADMIN_PANEL = True
CSRF_COOKIE_SAMESITE = "Strict"
SESSION_COOKIE_SAMESITE = "Strict"
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_AGE = 1000 * 60
